# =============================
# APP CONFIG
# =============================
spring.application.name=Password Manager
# Porta padr\u00e3o, sem servidor web ativo
server.port=8080

# =============================
# DATABASE (LOCAL H2)
# =============================
#spring.datasource.url=jdbc:h2:mem:testdb \\ Modo de mem\u00f3ria tempor\u00e1ria
spring.datasource.url=jdbc:h2:file:./data/passwordmanager-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mant\u00e9m as tabelas e dados entre execu\u00e7\u00f5es
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita console web para inspe\u00e7\u00e3o manual (acesso em: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Por padr\u00e3o, desligado (CLI limpa)
spring.jpa.show-sql=false
# Mas pode ativar temporariamente quando quiser ver queries:
# spring.jpa.show-sql=true

# =============================
# SPRING BOOT STARTUP
# =============================
# Remove banner do Spring
spring.main.banner-mode=off

# Evita logs de inicializa\u00e7\u00e3o (beans, tempo de boot etc.)
spring.main.log-startup-info=false

# =============================
# LOGGING
# =============================
# N\u00edvel raiz \u2014 apenas erros cr\u00edticos do Spring
logging.level.root=ERROR

logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache.catalina=ERROR          
logging.level.org.springframework.boot=ERROR
logging.level.org.springframework.boot.startup=OFF
logging.level.com.zaxxer.hikari=ERROR            
logging.level.org.hyperledger=ERROR

# Permite que apenas seus logs (da aplica\u00e7\u00e3o) apare\u00e7am normalmente
logging.level.com.tcc.password_manager=INFO
